(()=>{
  const typeMenu=document.getElementById('typeMenu'),routeMenu=document.getElementById('routeMenu'),routeDetail=document.getElementById('routeDetail'),types=document.getElementById('types'),routesGrid=document.getElementById('routes'),routeMenuTitle=document.getElementById('routeMenuTitle'),routeCount=document.getElementById('routeCount'),routeHint=document.getElementById('routeHint'),backToTypes=document.getElementById('backToTypes'),backToRoutes=document.getElementById('backToRoutes'),sectionBacks=[...document.querySelectorAll('[data-schedule-back]')],loading=document.getElementById('loading'),content=document.getElementById('routeContent'),routeTitle=document.getElementById('routeTitle'),routeMeta=document.getElementById('routeMeta'),fare=document.getElementById('fare'),directions=document.getElementById('directions'),viewTabs=document.getElementById('viewTabs'),schedulePanel=document.getElementById('schedulePanel'),mapView=document.getElementById('mapView'),stopsView=document.getElementById('stopsView'),cityTitle=document.getElementById('cityTitle'),citySubtitle=document.getElementById('citySubtitle'),menuTitle=document.getElementById('menuTitle'),cityCoverImage=document.getElementById('cityCoverImage');
  const query=new URLSearchParams(location.search);
  const cityKey=query.get('city')||'villages';
  const safeCityKey=/^[a-z]+$/.test(cityKey)?cityKey:'villages';
  const cityMeta={
    izmail:{place:'Измаил',title:'Расписание · Измаил',subtitle:'Городские автобусы · города · сёла',cover:'izmail-v2.webp?v=2',urban:{title:'Городские автобусы',subtitle:'16 маршрутов · время · карты движения',href:'../bus-schedule/',icon:'🚌'}},
    odesa:{place:'Одесса',title:'Расписание · Одесса',subtitle:'Городской транспорт · направления по области',cover:'odesa-v2.webp?v=2',urban:{title:'Городской транспорт Одессы',subtitle:'Автобусы · троллейбусы · трамваи',href:'../odessa-schedule/',icon:'🚋'}},
    kiliya:{place:'Килия'},vilkove:{place:'Вилково'},reni:{place:'Рени'},bolgrad:{place:'Болград'},artsyz:{place:'Арциз'},tatarbunary:{place:'Татарбунары'},bilhorod:{place:'Белгород-Днестровский'},kyiv:{place:'Киев'},villages:{place:''}
  };
  const meta=cityMeta[safeCityKey]||cityMeta.villages;
  let data=null,regional=[],activeGroup=null,activeRoute=null,activeDirection=0,activeView='schedule',activePlace='';
  const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const normalize=value=>String(value||'').toLocaleLowerCase('ru').replace(/ё/g,'е').replace(/[ії]/g,'и').replace(/є/g,'е').replace(/[^a-zа-я0-9]+/gi,' ').trim();
  const plural=(count,one,few,many)=>{const mod100=count%100,mod10=count%10;return mod100>=11&&mod100<=19?many:mod10===1?one:mod10>=2&&mod10<=4?few:many};
  const villagePhotos={'Сафьяны':'safiany','Матроска':'matroska','Ларжанка':'larzhanka','Броска':'broska','Лощиновка':'loshchynivka','Новая Некрасовка':'nova-nekrasivka','Старая Некрасовка':'stara-nekrasivka','Кислица':'kyslytsia','Муравлёвка':'muravlivka','Озёрное':'ozerne','Богатое':'bohate','Утконосовка':'utkonosivka','Криничное':'krynychne','Дунайское':'dunaiske','Первомайское':'pershotravneve','Новокаланчак':'novokalanchak','Камышовка':'kamyshovka','Новосёловка':'novoselivka','Дмитровка':'dmytrivka'};
  const villageIcon='<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4M17 3v4M3 10h18M8 15h3M14 15h2M8 18h2"/></svg>';
  const displayRoute=id=>String(id).replace(/^C/,'С');
  const directionStartsAt=(direction,place)=>normalize(direction?.stops?.[0]?.name)===normalize(place);
  const relatedRoutes=place=>regional.flatMap(route=>{
    if(!route.places.some(item=>normalize(item)===normalize(place)))return [];
    const directions=(route.directions||[]).filter(direction=>directionStartsAt(direction,place));
    if(!directions.length)return [];
    const destinations=(route.places||[]).filter(item=>normalize(item)!==normalize(place));
    return [{...route,name:[place,...destinations].join(' — '),directions}];
  });
  const routeButtonLabel=route=>{const place=activePlace||meta.place;const others=(route.places||[]).filter(item=>normalize(item)!==normalize(place));return others.length?others.join(' · '):route.name||route.id};
  function scrollHere(){requestAnimationFrame(()=>document.querySelector('.nav-row').scrollIntoView({block:'start'}))}
  function setSectionBack(label){sectionBacks.forEach(link=>link.querySelector('[data-schedule-back-label]').textContent=label)}
  function setCoverForVillage(place){cityCoverImage.src=`../../assets/schedule-villages/${villagePhotos[place]}.webp?v=1`;cityCoverImage.alt=place;cityTitle.textContent='Расписание · '+place;citySubtitle.textContent='Все доступные направления и время отправления'}
  function showTypes(){activeGroup=null;activeRoute=null;activePlace='';routeMenu.hidden=true;routeDetail.hidden=true;typeMenu.hidden=false;setSectionBack('Вернуться в раздел');scrollHere()}
  function buildTypes(){types.innerHTML=data.groups.map(group=>group.href?`<a class="type-card" href="${escapeHtml(group.href)}"><span class="type-icon" aria-hidden="true">${group.icon}</span><span class="type-copy"><strong>${escapeHtml(group.title)}</strong><span>${escapeHtml(group.subtitle)}</span></span><span class="chevron" aria-hidden="true">›</span></a>`:`<button class="type-card" type="button" data-type="${escapeHtml(group.id)}"><span class="type-icon" aria-hidden="true">${group.icon}</span><span class="type-copy"><strong>${escapeHtml(group.title)}</strong><span>${group.routes.length} ${plural(group.routes.length,'маршрут','маршрута','маршрутов')}</span></span><span class="chevron" aria-hidden="true">›</span></button>`).join('');types.querySelectorAll('[data-type]').forEach(button=>button.addEventListener('click',()=>showRoutes(button.dataset.type)))}
  function renderRouteMenu(group,{villageOverview=false}={}){
    activeGroup=group;activeRoute=null;typeMenu.hidden=true;routeDetail.hidden=true;routeMenu.hidden=false;
    const usesTransportTypes=safeCityKey==='kyiv';setSectionBack(usesTransportTypes?'Виды транспорта':'Вернуться в раздел');backToTypes.hidden=villageOverview;backToTypes.innerHTML=activePlace?'<span aria-hidden="true">←</span> Все сёла':'<span aria-hidden="true">←</span> Виды транспорта';routeMenuTitle.textContent=group.title;routeHint.textContent=villageOverview?'Выберите село.':'Выберите направление.';routeCount.textContent=group.routes.length+' '+plural(group.routes.length,'маршрут','маршрута','маршрутов');routesGrid.classList.toggle('named-routes',safeCityKey!=='kyiv'||group.id==='regional'||Boolean(activePlace));routesGrid.classList.toggle('village-routes',villageOverview);
    if(villageOverview){cityCoverImage.src='../../assets/schedule-cities/villages.jpg?v=1';cityCoverImage.alt=data.title;cityTitle.textContent=data.title;citySubtitle.textContent=data.subtitle}
    routesGrid.innerHTML=group.routes.length?group.routes.map(route=>villageOverview?`<button class="route village-route" type="button" data-village="${escapeHtml(route.id)}" aria-label="Расписание ${escapeHtml(displayRoute(route.id))}"><img class="village-route-photo" src="../../assets/schedule-villages/${villagePhotos[route.id]}.webp?v=1" alt="" loading="lazy"><span class="village-route-shade" aria-hidden="true"></span><span class="village-route-icon" aria-hidden="true">${villageIcon}</span><span class="village-route-name">${escapeHtml(displayRoute(route.id))}</span><span class="village-route-arrow" aria-hidden="true">›</span></button>`:`<button class="route" type="button" data-route="${escapeHtml(route.id)}" aria-label="Расписание ${escapeHtml(route.name||route.id)}">${escapeHtml(routeButtonLabel(route))}</button>`).join(''):`<p class="route-empty">Для ${escapeHtml(activePlace||meta.place)} не найдено опубликованного времени отправления.</p>`;
    routesGrid.querySelectorAll('[data-village]').forEach(button=>button.addEventListener('click',()=>showVillage(button.dataset.village)));routesGrid.querySelectorAll('[data-route]').forEach(button=>button.addEventListener('click',()=>showRoute(group.routes.find(route=>route.id===button.dataset.route))));scrollHere()
  }
  function showRoutes(groupId){const group=data.groups.find(item=>item.id===groupId);if(group)renderRouteMenu(group,{villageOverview:safeCityKey==='villages'&&!activePlace})}
  function showVillage(place){activePlace=place;setCoverForVillage(place);renderRouteMenu({id:'village-routes',title:'Направления · '+place,icon:'🚌',routes:relatedRoutes(place)})}
  function showRoute(route){activeRoute=route;activeDirection=0;activeView='schedule';routeMenu.hidden=true;routeDetail.hidden=false;if(activePlace)setCoverForVillage(activePlace);routeTitle.textContent=(activeGroup.icon||'🚌')+' '+(route.name||displayRoute(route.id));routeMeta.textContent=(route.name||displayRoute(route.id))+' · '+(route.days||'По расписанию');fare.textContent=route.fare||activeGroup.fare||'';fare.hidden=!fare.textContent;directions.innerHTML=route.directions.map((direction,index)=>`<button class="direction" type="button" data-direction="${index}" aria-pressed="${index===0}">Отправление: ${escapeHtml(direction.stops?.[0]?.name||direction.label)}</button>`).join('');directions.querySelectorAll('[data-direction]').forEach(button=>button.addEventListener('click',()=>setDirection(Number(button.dataset.direction))));setDirection(0);setView('schedule');scrollHere()}
  function setDirection(index){activeDirection=index;directions.querySelectorAll('.direction').forEach((button,buttonIndex)=>button.setAttribute('aria-pressed',String(buttonIndex===index)));renderDirection()}
  function renderDirection(){const direction=activeRoute.directions[activeDirection];const facts=[];if(direction.hours)facts.push(`<div class="fact"><span>Часы работы</span><strong>${escapeHtml(direction.hours)}</strong></div>`);if(direction.interval)facts.push(`<div class="fact"><span>Интервал</span><strong>${escapeHtml(direction.interval)} мин</strong></div>`);if(direction.departures.length)facts.push(`<div class="fact"><span>Первый рейс</span><strong>${escapeHtml(direction.departures[0])}</strong></div><div class="fact"><span>Последний рейс</span><strong>${escapeHtml(direction.departures.at(-1))}</strong></div>`);schedulePanel.innerHTML=`<div class="summary"><p class="route-name">${escapeHtml(direction.name)}</p>${facts.length?`<div class="facts">${facts.join('')}</div>`:''}${direction.departures.length?`<div class="departures">${direction.departures.map(time=>`<span class="departure">${escapeHtml(time)}</span>`).join('')}</div>`:''}${direction.extra?`<p class="extra">${escapeHtml(direction.extra)}</p>`:''}</div>`;renderMap(direction);renderStops(direction)}
  function renderMap(direction){window.IzmailRouteMap.mount(mapView,direction,{routeLabel:activeRoute.name||displayRoute(activeRoute.id)})}
  function renderStops(direction){stopsView.innerHTML=`<ol class="stops-list">${direction.stops.map(stop=>`<li>${escapeHtml(stop.name)}</li>`).join('')}</ol>`}
  function setView(view){activeView=view;viewTabs.querySelectorAll('[data-view]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.view===view)));schedulePanel.hidden=view!=='schedule';mapView.hidden=view!=='map';stopsView.hidden=view!=='stops';if(view==='map'){const frame=mapView.querySelector('iframe[data-src]');if(frame&&!frame.src)frame.src=frame.dataset.src}}
  function prepareData(payload,regionalPayload){regional=regionalPayload.routes||[];if(safeCityKey==='villages')return payload;const related=relatedRoutes(meta.place);const regionalGroup={id:'regional',title:'Все направления · '+meta.place,icon:'🚌',fare:'',routes:related};if(safeCityKey==='kyiv')return {...payload,groups:[...payload.groups,regionalGroup]};const groups=[];if(meta.urban)groups.push({id:'urban',...meta.urban,routes:[]});groups.push(regionalGroup);return {updated:regionalPayload.updated,title:meta.title||payload.title,subtitle:meta.subtitle||payload.subtitle,groups}}
  viewTabs.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.view)));backToTypes.addEventListener('click',()=>activePlace?(activePlace='',showRoutes(data.groups[0].id)):showTypes());sectionBacks.forEach(button=>button.addEventListener('click',()=>{if((safeCityKey==='kyiv'||meta.urban)&&activeGroup)showTypes();else location.href='../#schedule'}));backToRoutes.addEventListener('click',()=>activePlace?showVillage(activePlace):showRoutes(activeGroup.id));document.addEventListener('pointerdown',event=>{const control=event.target.closest('button,.back,.home-back,.type-card');if(!control)return;control.classList.add('tap-lit');setTimeout(()=>control.classList.remove('tap-lit'),420)},{passive:true});
  const cityCoverFile=meta.cover||(safeCityKey==='villages'?'villages.jpg?v=1':`${safeCityKey}-v2.webp?v=2`);cityCoverImage.src=`../../assets/schedule-cities/${cityCoverFile}`;
  const basePromise=meta.urban?Promise.resolve({title:meta.title,subtitle:meta.subtitle,groups:[]}):fetch(`./data/${safeCityKey}.json?v=20261001-2`,{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error('data');return response.json()});
  Promise.all([basePromise,fetch('./data/regional-routes.json?v=20261005-2',{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error('regional');return response.json()})]).then(([payload,regionalPayload])=>{data=prepareData(payload,regionalPayload);cityTitle.textContent=data.title;citySubtitle.textContent=data.subtitle;cityCoverImage.alt=data.title;menuTitle.textContent='Выберите направление';document.title=data.title+' — Справочник Измаил';buildTypes();loading.hidden=true;content.hidden=false;const requestedGroup=data.groups.find(item=>item.id===query.get('group')),requestedRoute=requestedGroup?.routes.find(item=>item.id===query.get('route'));if(safeCityKey==='villages'){const place=query.get('place');if(place&&villagePhotos[place]){showVillage(place);const route=activeGroup.routes.find(item=>item.id===query.get('route'));if(route)showRoute(route)}else{backToTypes.hidden=true;showRoutes(data.groups[0].id)}}else if(requestedGroup&&requestedRoute){showRoutes(requestedGroup.id);showRoute(requestedRoute)}}).catch(()=>{typeMenu.innerHTML='<p class="error">Не удалось загрузить расписание. Обновите страницу и попробуйте ещё раз.</p>'});
})();
